# this file is specific to portainer repository based deployments where gitops
# updates are enabled and the container image should be built from the local
# code checkout; due to limitations with setting/overriding environment
# variables, we have to define them all here, even if they will not be set, see
# https://docs.portainer.io/user/docker/stacks/add#environment-variables

services:
  streetmerchant:
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: build
    environment:
      # define environment variables found in ./src:
      # grep -Rh process.env. src | sed -nE 's#.+process.env.([A-Z0-9_]+).*#\1#p' | grep -vxE 'AUTO_ADD_TO_CART|DESKTOP_NOTIFICATIONS|DOCKER|HEADLESS|OPEN_BROWSER|PLAY_SOUND|SOUND_PLAYER' | sort | uniq | sed -E 's/(.+)/\1: ${\1:-}/'
      APNS_AUTHKEY: ${APNS_AUTHKEY:-}
      APNS_BUNDLEID: ${APNS_BUNDLEID:-}
      APNS_DEVICETOKEN: ${APNS_DEVICETOKEN:-}
      APNS_KEYID: ${APNS_KEYID:-}
      APNS_PRODUCTION: ${APNS_PRODUCTION:-}
      APNS_TEAMID: ${APNS_TEAMID:-}
      ASCII_BANNER: ${ASCII_BANNER:-}
      BANNER_COLOR: ${BANNER_COLOR:-}
      BROWSER_TRUSTED: ${BROWSER_TRUSTED:-}
      CAPTCHA_HANDLER_CAPTURE_TYPE: ${CAPTCHA_HANDLER_CAPTURE_TYPE:-}
      CAPTCHA_HANDLER_POLL_INTERVAL: ${CAPTCHA_HANDLER_POLL_INTERVAL:-}
      CAPTCHA_HANDLER_RESPONSE_TIMEOUT: ${CAPTCHA_HANDLER_RESPONSE_TIMEOUT:-}
      CAPTCHA_HANDLER_SERVICE: ${CAPTCHA_HANDLER_SERVICE:-}
      CAPTCHA_HANDLER_TOKEN: ${CAPTCHA_HANDLER_TOKEN:-}
      CAPTCHA_HANDLER_USER_ID: ${CAPTCHA_HANDLER_USER_ID:-}
      COOKIE_POLICY: ${COOKIE_POLICY:-}
      COUNTRY: ${COUNTRY:-}
      DISCORD_NOTIFY_GROUP: ${DISCORD_NOTIFY_GROUP:-}
      DISCORD_NOTIFY_GROUP_3050: ${DISCORD_NOTIFY_GROUP_3050:-}
      DISCORD_NOTIFY_GROUP_3060: ${DISCORD_NOTIFY_GROUP_3060:-}
      DISCORD_NOTIFY_GROUP_3060TI: ${DISCORD_NOTIFY_GROUP_3060TI:-}
      DISCORD_NOTIFY_GROUP_3070: ${DISCORD_NOTIFY_GROUP_3070:-}
      DISCORD_NOTIFY_GROUP_3070TI: ${DISCORD_NOTIFY_GROUP_3070TI:-}
      DISCORD_NOTIFY_GROUP_3080: ${DISCORD_NOTIFY_GROUP_3080:-}
      DISCORD_NOTIFY_GROUP_3080TI: ${DISCORD_NOTIFY_GROUP_3080TI:-}
      DISCORD_NOTIFY_GROUP_3090: ${DISCORD_NOTIFY_GROUP_3090:-}
      DISCORD_NOTIFY_GROUP_4060: ${DISCORD_NOTIFY_GROUP_4060:-}
      DISCORD_NOTIFY_GROUP_4070: ${DISCORD_NOTIFY_GROUP_4070:-}
      DISCORD_NOTIFY_GROUP_4070SUPER: ${DISCORD_NOTIFY_GROUP_4070SUPER:-}
      DISCORD_NOTIFY_GROUP_4070TI: ${DISCORD_NOTIFY_GROUP_4070TI:-}
      DISCORD_NOTIFY_GROUP_4080_16G: ${DISCORD_NOTIFY_GROUP_4080_16G:-}
      DISCORD_NOTIFY_GROUP_4090: ${DISCORD_NOTIFY_GROUP_4090:-}
      DISCORD_NOTIFY_GROUP_5070: ${DISCORD_NOTIFY_GROUP_5070:-}
      DISCORD_NOTIFY_GROUP_5070TI: ${DISCORD_NOTIFY_GROUP_5070TI:-}
      DISCORD_NOTIFY_GROUP_5080: ${DISCORD_NOTIFY_GROUP_5080:-}
      DISCORD_NOTIFY_GROUP_5090: ${DISCORD_NOTIFY_GROUP_5090:-}
      DISCORD_NOTIFY_GROUP_A3_MATX: ${DISCORD_NOTIFY_GROUP_A3_MATX:-}
      DISCORD_NOTIFY_GROUP_ARC: ${DISCORD_NOTIFY_GROUP_ARC:-}
      DISCORD_NOTIFY_GROUP_CORSAIR_SF: ${DISCORD_NOTIFY_GROUP_CORSAIR_SF:-}
      DISCORD_NOTIFY_GROUP_DARKHERO: ${DISCORD_NOTIFY_GROUP_DARKHERO:-}
      DISCORD_NOTIFY_GROUP_RX6700XT: ${DISCORD_NOTIFY_GROUP_RX6700XT:-}
      DISCORD_NOTIFY_GROUP_RX6800: ${DISCORD_NOTIFY_GROUP_RX6800:-}
      DISCORD_NOTIFY_GROUP_RX6800XT: ${DISCORD_NOTIFY_GROUP_RX6800XT:-}
      DISCORD_NOTIFY_GROUP_RX6900XT: ${DISCORD_NOTIFY_GROUP_RX6900XT:-}
      DISCORD_NOTIFY_GROUP_RYZEN5600: ${DISCORD_NOTIFY_GROUP_RYZEN5600:-}
      DISCORD_NOTIFY_GROUP_RYZEN5800: ${DISCORD_NOTIFY_GROUP_RYZEN5800:-}
      DISCORD_NOTIFY_GROUP_RYZEN5900: ${DISCORD_NOTIFY_GROUP_RYZEN5900:-}
      DISCORD_NOTIFY_GROUP_RYZEN5950: ${DISCORD_NOTIFY_GROUP_RYZEN5950:-}
      DISCORD_NOTIFY_GROUP_RYZEN7800X3D: ${DISCORD_NOTIFY_GROUP_RYZEN7800X3D:-}
      DISCORD_NOTIFY_GROUP_RYZEN7950X: ${DISCORD_NOTIFY_GROUP_RYZEN7950X:-}
      DISCORD_NOTIFY_GROUP_RYZEN9600X: ${DISCORD_NOTIFY_GROUP_RYZEN9600X:-}
      DISCORD_NOTIFY_GROUP_RYZEN9700X: ${DISCORD_NOTIFY_GROUP_RYZEN9700X:-}
      DISCORD_NOTIFY_GROUP_RYZEN9800X3D: ${DISCORD_NOTIFY_GROUP_RYZEN9800X3D:-}
      DISCORD_NOTIFY_GROUP_RYZEN9900X: ${DISCORD_NOTIFY_GROUP_RYZEN9900X:-}
      DISCORD_NOTIFY_GROUP_RYZEN9950X: ${DISCORD_NOTIFY_GROUP_RYZEN9950X:-}
      DISCORD_NOTIFY_GROUP_SONYPS5C: ${DISCORD_NOTIFY_GROUP_SONYPS5C:-}
      DISCORD_NOTIFY_GROUP_SONYPS5DE: ${DISCORD_NOTIFY_GROUP_SONYPS5DE:-}
      DISCORD_NOTIFY_GROUP_TEST: ${DISCORD_NOTIFY_GROUP_TEST:-}
      DISCORD_NOTIFY_GROUP_XBOXSS: ${DISCORD_NOTIFY_GROUP_XBOXSS:-}
      DISCORD_NOTIFY_GROUP_XBOXSX: ${DISCORD_NOTIFY_GROUP_XBOXSX:-}
      DISCORD_WEB_HOOK: ${DISCORD_WEB_HOOK:-}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD:-}
      EMAIL_TO: ${EMAIL_TO:-}
      EMAIL_USERNAME: ${EMAIL_USERNAME:-}
      FREEMOBILE_API_KEY: ${FREEMOBILE_API_KEY:-}
      FREEMOBILE_ID: ${FREEMOBILE_ID:-}
      GOTIFY_PRIORITY: ${GOTIFY_PRIORITY:-}
      GOTIFY_TOKEN: ${GOTIFY_TOKEN:-}
      GOTIFY_URL: ${GOTIFY_URL:-}
      IN_STOCK_WAIT_TIME: ${IN_STOCK_WAIT_TIME:-}
      LANGUAGE: ${LANGUAGE:-}
      LOG_LEVEL: ${LOG_LEVEL:-}
      LOW_BANDWIDTH: ${LOW_BANDWIDTH:-}
      LOW_BANDWIDTH_MODE: ${LOW_BANDWIDTH_MODE:-}
      MAX_PRICE: ${MAX_PRICE:-}
      MAX_PRICE_SERIES_3050: ${MAX_PRICE_SERIES_3050:-}
      MAX_PRICE_SERIES_3060: ${MAX_PRICE_SERIES_3060:-}
      MAX_PRICE_SERIES_3060TI: ${MAX_PRICE_SERIES_3060TI:-}
      MAX_PRICE_SERIES_3070: ${MAX_PRICE_SERIES_3070:-}
      MAX_PRICE_SERIES_3070TI: ${MAX_PRICE_SERIES_3070TI:-}
      MAX_PRICE_SERIES_3080: ${MAX_PRICE_SERIES_3080:-}
      MAX_PRICE_SERIES_3080TI: ${MAX_PRICE_SERIES_3080TI:-}
      MAX_PRICE_SERIES_3090: ${MAX_PRICE_SERIES_3090:-}
      MAX_PRICE_SERIES_4060: ${MAX_PRICE_SERIES_4060:-}
      MAX_PRICE_SERIES_4070: ${MAX_PRICE_SERIES_4070:-}
      MAX_PRICE_SERIES_4070SUPER: ${MAX_PRICE_SERIES_4070SUPER:-}
      MAX_PRICE_SERIES_4070TI: ${MAX_PRICE_SERIES_4070TI:-}
      MAX_PRICE_SERIES_4080_16G: ${MAX_PRICE_SERIES_4080_16G:-}
      MAX_PRICE_SERIES_4090: ${MAX_PRICE_SERIES_4090:-}
      MAX_PRICE_SERIES_5070: ${MAX_PRICE_SERIES_5070:-}
      MAX_PRICE_SERIES_5070TI: ${MAX_PRICE_SERIES_5070TI:-}
      MAX_PRICE_SERIES_5080: ${MAX_PRICE_SERIES_5080:-}
      MAX_PRICE_SERIES_5090: ${MAX_PRICE_SERIES_5090:-}
      MAX_PRICE_SERIES_A3_MATX: ${MAX_PRICE_SERIES_A3_MATX:-}
      MAX_PRICE_SERIES_ARC: ${MAX_PRICE_SERIES_ARC:-}
      MAX_PRICE_SERIES_CORSAIR_SF: ${MAX_PRICE_SERIES_CORSAIR_SF:-}
      MAX_PRICE_SERIES_DARKHERO: ${MAX_PRICE_SERIES_DARKHERO:-}
      MAX_PRICE_SERIES_G4_DOORBELL_PRO: ${MAX_PRICE_SERIES_G4_DOORBELL_PRO:-}
      MAX_PRICE_SERIES_RX6700XT: ${MAX_PRICE_SERIES_RX6700XT:-}
      MAX_PRICE_SERIES_RX6800: ${MAX_PRICE_SERIES_RX6800:-}
      MAX_PRICE_SERIES_RX6800XT: ${MAX_PRICE_SERIES_RX6800XT:-}
      MAX_PRICE_SERIES_RX6900XT: ${MAX_PRICE_SERIES_RX6900XT:-}
      MAX_PRICE_SERIES_RYZEN5600: ${MAX_PRICE_SERIES_RYZEN5600:-}
      MAX_PRICE_SERIES_RYZEN5800: ${MAX_PRICE_SERIES_RYZEN5800:-}
      MAX_PRICE_SERIES_RYZEN5900: ${MAX_PRICE_SERIES_RYZEN5900:-}
      MAX_PRICE_SERIES_RYZEN5950: ${MAX_PRICE_SERIES_RYZEN5950:-}
      MAX_PRICE_SERIES_RYZEN7800X3D: ${MAX_PRICE_SERIES_RYZEN7800X3D:-}
      MAX_PRICE_SERIES_RYZEN7950X: ${MAX_PRICE_SERIES_RYZEN7950X:-}
      MAX_PRICE_SERIES_RYZEN9600X: ${MAX_PRICE_SERIES_RYZEN9600X:-}
      MAX_PRICE_SERIES_RYZEN9700X: ${MAX_PRICE_SERIES_RYZEN9700X:-}
      MAX_PRICE_SERIES_RYZEN9800X3D: ${MAX_PRICE_SERIES_RYZEN9800X3D:-}
      MAX_PRICE_SERIES_RYZEN9900X: ${MAX_PRICE_SERIES_RYZEN9900X:-}
      MAX_PRICE_SERIES_RYZEN9950X: ${MAX_PRICE_SERIES_RYZEN9950X:-}
      MAX_PRICE_SERIES_SONYPS5C: ${MAX_PRICE_SERIES_SONYPS5C:-}
      MAX_PRICE_SERIES_SONYPS5DE: ${MAX_PRICE_SERIES_SONYPS5DE:-}
      MAX_PRICE_SERIES_TEST: ${MAX_PRICE_SERIES_TEST:-}
      MAX_PRICE_SERIES_UDM_PRO: ${MAX_PRICE_SERIES_UDM_PRO:-}
      MAX_PRICE_SERIES_UDM_US: ${MAX_PRICE_SERIES_UDM_US:-}
      MAX_PRICE_SERIES_UDR_US: ${MAX_PRICE_SERIES_UDR_US:-}
      MAX_PRICE_SERIES_UNVR: ${MAX_PRICE_SERIES_UNVR:-}
      MAX_PRICE_SERIES_UNVR_PRO: ${MAX_PRICE_SERIES_UNVR_PRO:-}
      MAX_PRICE_SERIES_XBOXSS: ${MAX_PRICE_SERIES_XBOXSS:-}
      MAX_PRICE_SERIES_XBOXSX: ${MAX_PRICE_SERIES_XBOXSX:-}
      MICROCENTER_LOCATION: ${MICROCENTER_LOCATION:-}
      MQTT_BROKER_ADDRESS: ${MQTT_BROKER_ADDRESS:-}
      MQTT_BROKER_PORT: ${MQTT_BROKER_PORT:-}
      MQTT_CLIENT_ID: ${MQTT_CLIENT_ID:-}
      MQTT_PASSWORD: ${MQTT_PASSWORD:-}
      MQTT_QOS: ${MQTT_QOS:-}
      MQTT_TOPIC: ${MQTT_TOPIC:-}
      MQTT_USERNAME: ${MQTT_USERNAME:-}
      NTFY_ACCESS_TOKEN: ${NTFY_ACCESS_TOKEN:-}
      NTFY_PRIORITY: ${NTFY_PRIORITY:-}
      NTFY_TITLE: ${NTFY_TITLE:-}
      NTFY_TOPIC: ${NTFY_TOPIC:-}
      NTFY_URL: ${NTFY_URL:-}
      NVIDIA_ADD_TO_CART_ATTEMPTS: ${NVIDIA_ADD_TO_CART_ATTEMPTS:-}
      NVIDIA_SESSION_TTL: ${NVIDIA_SESSION_TTL:-}
      PAGERDUTY_INTEGRATION_KEY: ${PAGERDUTY_INTEGRATION_KEY:-}
      PAGERDUTY_SEVERITY: ${PAGERDUTY_SEVERITY:-}
      PAGE_BACKOFF_MAX: ${PAGE_BACKOFF_MAX:-}
      PAGE_BACKOFF_MIN: ${PAGE_BACKOFF_MIN:-}
      PAGE_SLEEP_MAX: ${PAGE_SLEEP_MAX:-}
      PAGE_SLEEP_MIN: ${PAGE_SLEEP_MIN:-}
      PAGE_TIMEOUT: ${PAGE_TIMEOUT:-}
      PHILIPS_HUE_API_KEY: ${PHILIPS_HUE_API_KEY:-}
      PHILIPS_HUE_CLOUD_ACCESS_TOKEN: ${PHILIPS_HUE_CLOUD_ACCESS_TOKEN:-}
      PHILIPS_HUE_CLOUD_CLIENT_ID: ${PHILIPS_HUE_CLOUD_CLIENT_ID:-}
      PHILIPS_HUE_CLOUD_CLIENT_SECRET: ${PHILIPS_HUE_CLOUD_CLIENT_SECRET:-}
      PHILIPS_HUE_CLOUD_REFRESH_TOKEN: ${PHILIPS_HUE_CLOUD_REFRESH_TOKEN:-}
      PHILIPS_HUE_LAN_BRIDGE_IP: ${PHILIPS_HUE_LAN_BRIDGE_IP:-}
      PHILIPS_HUE_LIGHT_COLOR: ${PHILIPS_HUE_LIGHT_COLOR:-}
      PHILIPS_HUE_LIGHT_IDS: ${PHILIPS_HUE_LIGHT_IDS:-}
      PHILIPS_HUE_LIGHT_PATTERN: ${PHILIPS_HUE_LIGHT_PATTERN:-}
      PHONE_CARRIER: ${PHONE_CARRIER:-}
      PHONE_NUMBER: ${PHONE_NUMBER:-}
      PROXY_ADDRESS: ${PROXY_ADDRESS:-}
      PROXY_LIST: ${PROXY_LIST:-}
      PROXY_PASSWORD: ${PROXY_PASSWORD:-}
      PROXY_PORT: ${PROXY_PORT:-}
      PROXY_PROTOCOL: ${PROXY_PROTOCOL:-}
      PROXY_USERNAME: ${PROXY_USERNAME:-}
      PUPPETEER_EXECUTABLE_PATH: ${PUPPETEER_EXECUTABLE_PATH:-/usr/bin/google-chrome}
      PUSHBULLET: ${PUSHBULLET:-}
      PUSHOVER_DEVICE: ${PUSHOVER_DEVICE:-}
      PUSHOVER_EXPIRE: ${PUSHOVER_EXPIRE:-}
      PUSHOVER_PRIORITY: ${PUSHOVER_PRIORITY:-}
      PUSHOVER_RETRY: ${PUSHOVER_RETRY:-}
      PUSHOVER_SOUND: ${PUSHOVER_SOUND:-}
      PUSHOVER_TOKEN: ${PUSHOVER_TOKEN:-}
      PUSHOVER_USER: ${PUSHOVER_USER:-}
      REDIS_URL: ${REDIS_URL:-}
      RESTART_TIME: ${RESTART_TIME:-}
      SCREENSHOT: ${SCREENSHOT:-}
      SCREENSHOT_DIR: ${SCREENSHOT_DIR:-}
      SCREENSHOT_FULL_PAGE: ${SCREENSHOT_FULL_PAGE:-}
      SHOW_ONLY_BRANDS: ${SHOW_ONLY_BRANDS:-}
      SHOW_ONLY_COUNTRY: ${SHOW_ONLY_COUNTRY:-}
      SHOW_ONLY_MODELS: ${SHOW_ONLY_MODELS:-}
      SHOW_ONLY_SERIES: ${SHOW_ONLY_SERIES:-}
      SLACK_CHANNEL: ${SLACK_CHANNEL:-}
      SLACK_TOKEN: ${SLACK_TOKEN:-}
      SMTP_ADDRESS: ${SMTP_ADDRESS:-}
      SMTP_PORT: ${SMTP_PORT:-}
      STORES: ${STORES:-}
      STREAMLABS_ACCESS_TOKEN: ${STREAMLABS_ACCESS_TOKEN:-}
      STREAMLABS_DURATION: ${STREAMLABS_DURATION:-}
      STREAMLABS_IMAGE: ${STREAMLABS_IMAGE:-}
      STREAMLABS_SOUND: ${STREAMLABS_SOUND:-}
      STREAMLABS_TYPE: ${STREAMLABS_TYPE:-}
      TELEGRAM_ACCESS_TOKEN: ${TELEGRAM_ACCESS_TOKEN:-}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID:-}
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID:-}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN:-}
      TWILIO_FROM_NUMBER: ${TWILIO_FROM_NUMBER:-}
      TWILIO_TO_NUMBER: ${TWILIO_TO_NUMBER:-}
      TWITCH_ACCESS_TOKEN: ${TWITCH_ACCESS_TOKEN:-}
      TWITCH_CHANNEL: ${TWITCH_CHANNEL:-}
      TWITCH_CLIENT_ID: ${TWITCH_CLIENT_ID:-}
      TWITCH_CLIENT_SECRET: ${TWITCH_CLIENT_SECRET:-}
      TWITCH_REFRESH_TOKEN: ${TWITCH_REFRESH_TOKEN:-}
      TWITTER_ACCESS_TOKEN_KEY: ${TWITTER_ACCESS_TOKEN_KEY:-}
      TWITTER_ACCESS_TOKEN_SECRET: ${TWITTER_ACCESS_TOKEN_SECRET:-}
      TWITTER_CONSUMER_KEY: ${TWITTER_CONSUMER_KEY:-}
      TWITTER_CONSUMER_SECRET: ${TWITTER_CONSUMER_SECRET:-}
      TWITTER_TWEET_TAGS: ${TWITTER_TWEET_TAGS:-}
      TZ: ${TZ:-}
      USER_AGENT: ${USER_AGENT:-}
      USER_AGENT_KEEP_DEFAULT: ${USER_AGENT_KEEP_DEFAULT:-}
      WEB_PORT: ${WEB_PORT:-}
    restart: unless-stopped
