name: Continuous Integration
on:
  pull_request:
    branches:
      - main
jobs:
  build_lint:
    name: Build and lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile --strict-peer-dependencies
      - name: Compile TypeScript
        run: pnpm run compile
      - name: Run linter
        run: pnpm run lint
  build_docker:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run paths filter
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            build:
              - 'Dockerfile'
              - 'package*.json'
      - name: Build Docker image
        if: steps.filter.outputs.build == 'true'
        run: docker build .
